Q1. What is a database? Differentiate between SQL and NoSQL databases.

A database is an organized collection of data, so that it can be easily accessed and managed.
 SQL databases are table-based, while NoSQL databases are non-relational.
 SQL or relational models work better with structured data. This is because structured data is easy to search and analyze, much like data that is laid out in a table with columns and rows.
NoSQL models make sense for less structured data sets because it doesnâ€™t rely on a predefined model to analyze the data.
SQL databases tend to be able to execute more complex queries than NoSQL databases
SQL is more straightforward, while NoSQL offers more complex data storage solutions
SQL Examples: MySQL, PostgreSQL, Oracle, MS-SQL Server, NoSQL Examples: MongoDB, GraphQL, HBase, Neo4j, Cassandra

Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

DDL stadnd fror Data Definition Language,Data Definition Language actually consists of the SQL commands that can be used to define the database schema.
CREATE: This command is used to create the database or its objects (like table, index, function, views, store procedure, and triggers).
DROP: This command is used to delete objects from the database.
ALTER: This is used to alter the structure of the database.
TRUNCATE: This is used to remove all records from a table, including all spaces allocated for the records are removed.

Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

DML stand for Data Manipulation Language , The SQL commands that deals with the manipulation of data present in the database belong to DML.
INSERT : It is used to insert data into a table.
UPDATE: It is used to update existing data within a table.
DELETE : It is used to delete records from a database table.

Q4. What is DQL? Explain SELECT with an example.

DQL stand for Data Query Language,DQL statements are used for performing queries on the data within schema objects.
SELECT: It is used to retrieve data from the database

Q5. Explain Primary Key and Foreign Key.

A primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values. It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. 
A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. It is a column (or columns) that references a column (most often the primary key) of another table.

Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

import mysql.connector
# import mysql.connector
#create user 'user'@'%' identified by 'password'
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("Create database")
his method executes the given database operation (query or command). The parameters found in the tuple or dictionary params are bound to the variables in the operation. Specify variables using %s or %(name)s parameter style (that is, using format or pyformat style). execute() returns an iterator if multi is True.

Q7. Give the order of execution of SQL clauses in an SQL query.

 SQL query starts with finding the data first and then moves to filter it based on conditions specified. Below is the order of execution of SQL commands

1. From and Joins : since these two forms the basis of the query
2. Where : Filters out the rows
3. Group By : Grouping values based on the column specified in the Group By clause
4. Having : Filters out the grouped rows
5. Select
6. Distinct : Rows with duplicate values in the column marked as Distinct are discarded
7. Order By : Rows are sorted based on Order By clause
8. Limit, Offset : Finally the limit or offset is applied